const dwLocations = [
  {
    area: 'dw-village',
    name: 'Mothula',
    requirement: 'mearl-firerod',
    x: 30,
    y: 30,
  },
  {
    area: 'dw-village',
    name: 'Skull Woods',
    x: 160,
    y: 150,
  },
  {
    area: 'dw-village',
    name: 'Dark Lumberjack Hut',
    x: 320,
    y: 20,
  },
  {
    area: 'bumper-cave-bottom',
    name: 'Bumper Cave Bottom',
    x: 320,
    y: 170,
  },
  {
    area: 'bumper-cave-top',
    name: 'Bumper Cave Top',
    x: 310,
    y: 120,
  },
  {
    area: 'bumper-cave-top',
    name: 'Bumper Cave Item',
    type: 'item',
    x: 250,
    y: 140,
  },
  {
    area: 'dw-village',
    name: 'Village of Outcasts Fortune Teller',
    x: 160,
    y: 290,
  },
  {
    area: 'dw-village',
    name: 'Dark Sanctuary',
    x: 440,
    y: 260,
  },
  {
    area: 'dark-potion-shop',
    name: 'Dark Potion Shop',
    x: 780,
    y: 320,
  },
  {
    area: 'dw-village',
    itemCount: 1,
    name: 'Chest Game',
    x: 40,
    y: 450,
  },
  {
    area: 'dw-village',
    name: 'Thieves\' Town ',
    requirement: 'mearl',
    x: 120,
    y: 450,
  },
  {
    area: 'dw-village',
    itemCount: 1,
    name: 'C-shaped House',
    x: 190,
    y: 450,
  },
  {
    area: 'dw-village-shop',
    name: 'Village of Outcasts Shop',
    x: 190,
    y: 510,
  },
  {
    area: 'dw-village',
    itemCount: 1,
    name: 'Brewery',
    requirement: 'mearl',
    x: 90,
    y: 570,
  },
  {
    area: 'dw-village',
    name: 'Curiosity Shop',
    x: 300,
    y: 430,
  },
  {
    area: 'hammer-pegs',
    name: 'Purple Chest',
    requirement: 'mearl-smith-glove+',
    type: 'item',
    x: 290,
    y: 500,
  },
  {
    area: 'hammer-pegs',
    itemCount: 1,
    name: 'Hammer Pegs',
    requirement: 'mearl-hammer',
    x: 290,
    y: 580,
  },
  {
    area: 'swamp-palace',
    name: 'Arrow Game',
    x: 200,
    y: 690,
  },
  {
    area: 'swamp-palace',
    name: 'Dig Game',
    requirement: 'mearl',
    type: 'item',
    x: 20,
    y: 700,
  },
  {
    area: 'stumpy',
    name: 'Stumpy',
    type: 'item',
    x: 290,
    y: 650,
  },
  {
    area: 'pyramid',
    itemCount: 2,
    name: 'Pyramid Fairy',
    requirement: 'bigbomb',
    x: 450,
    y: 450,
  },
  {
    area: 'pyramid',
    name: 'Pyramid',
    requirement: 'gt',
    type: 'drop',
    x: 480,
    y: 390,
  },
  {
    area: 'pyramid',
    name: 'Pyramid Ledge',
    type: 'item',
    x: 580,
    y: 420,
  },
  {
    area: 'swamp-palace',
    name: 'Dark Link Bonk Rocks',
    requirement: 'mearl-boots',
    x: 470,
    y: 650,
  },
  {
    area: 'swamp-palace',
    name: 'Bomb Shop',
    x: 530,
    y: 670,
  },
  {
    area: 'swamp-palace',
    itemCount: 5,
    name: 'Hype Cave',
    requirement: 'mearl',
    x: 580,
    y: 760,
  },
  {
    area: 'swamp-palace',
    name: 'Swamp Palace',
    x: 450,
    y: 920,
  },
  {
    area: 'mire',
    name: 'Dark Agina',
    x: 190,
    y: 810,
  },
  {
    area: 'mire',
    medallionLocked: true,
    name: 'Misery Mire',
    requirement: 'mearl-medallion',
    x: 65,
    y: 820,
  },
  {
    area: 'mire',
    itemCount: 2,
    name: 'Mire Shed West',
    x: 10,
    y: 780,
  },
  {
    area: 'mire',
    name: 'Mire Shed East',
    x: 120,
    y: 780,
  },
  {
    area: 'swamp-palace',
    name: 'Dark Lake Shop',
    x: 630,
    y: 800,
  },
  {
    area: 'ice-palace',
    name: 'Ice Palace',
    x: 770,
    y: 840,
  },
  {
    area: 'dark-shopping-mall',
    name: 'Dark Ice Rod Cave',
    requirement: 'mearl',
    x: 880,
    y: 780,
  },
  {
    area: 'dark-shopping-mall',
    name: 'Dark Good Bee',
    x: 940,
    y: 780,
  },
  {
    area: 'dark-shopping-mall',
    name: 'Dark 20 Rupee Cave',
    requirement: 'mearl-glove',
    x: 910,
    y: 830,
  },
  {
    area: 'pyramid',
    name: 'Palace of Darkness Fairy',
    x: 810,
    y: 640,
  },
  {
    area: 'pyramid',
    name: 'Palace of Darkness Portal',
    x: 950,
    y: 695,
  },
  {
    area: 'pyramid',
    name: 'Palace of Darkness Hint',
    x: 830,
    y: 480,
  },
  {
    area: 'pyramid',
    name: 'Palace of Darkness',
    requirement: 'mearl',
    x: 940,
    y: 400,
  },
  {
    area: 'catfish',
    name: 'Catfish',
    requirement: 'mearl',
    type: 'item',
    x: 920,
    y: 160,
  },
  {
    area: 'ddm-top',
    name: 'Gannon\'s Tower',
    requirement: 'crystals',
    x: 540,
    y: 10,
  },
  {
    area: 'ddm-west',
    itemCount: 1,
    name: 'Spike Cave',
    poiName: 'spike',
    x: 550,
    y: 130,
  },
  {
    area: 'ddm-west',
    name: 'Dark Death Mountain Fairy',
    x: 380,
    y: 150,
  },
  {
    area: 'ddm-floating-island',
    name: 'Hookshot Exit',
    x: 720,
    y: 10,
  },
  {
    area: 'ddm-top',
    itemCount: 4,
    name: 'Hookshot Entrance',
    poiName: 'hookshot-cave-entrance',
    requirement: 'mearl-glove',
    x: 780,
    y: 20,
  },
  {
    area: 'ddm-top',
    itemCount: 2,
    name: 'Superbunny Top',
    poiName: 'superbunny-top',
    x: 840,
    y: 20,
  },
  {
    area: 'ddm-east',
    name: 'Dark Death Mountain Shop',
    x: 830,
    y: 180,
  },
  {
    area: 'ddm-east',
    name: 'Superbunny Bottom',
    x: 780,
    y: 180,
  },
  {
    area: 'tr-back',
    name: 'Turtle Rock Back',
    x: 790,
    y: 130,
  },
  {
    area: 'tr-connector-ledge',
    name: 'Turtle Rock East',
    x: 830,
    y: 80,
  },
  {
    area: 'tr-connector-ledge',
    name: 'Turtle Rock West',
    x: 750,
    y: 80,
  },
  {
    area: 'ddm-top', // needs to be its own area connected by a leap to ddm-top
    medallionLocked: true,
    name: 'Turtle Rock Main',
    requirement: 'mearl-medallion',
    x: 920,
    y: 40,
  },
];
