const dungeonData = [
  {name: 'HC', keys: 0, items: 6, noBigKey: true, noPrize: true},
  {name: 'EP', keys: 0, items: 3, noBigKey: true},
  {name: 'DP', keys: 0, items: 2, noBigKey: true},
  {name: 'TH', keys: 0, items: 2, noBigKey: true},
  {name: 'CT', keys: 0, items:0, noBigKey: true, noPrize: true},
  {name: 'PD', keys: 0, items: 5, noBigKey: true},
  {name: 'SP', keys: 0, items: 6, noBigKey: true},
  {name: 'SW', keys: 0, items: 2, noBigKey: true},
  {name: 'TT', keys: 0, items: 4, noBigKey: true},
  {name: 'IP', keys: 0, items: 3, noBigKey: true},
  {name: 'MM', keys: 0, items: 2, noBigKey: true},
  {name: 'TR', keys: 0, items: 5, noBigKey: true},
  {name: 'GT', keys: 0, items: 20, noBigKey: true, noPrize: true},
];
