const totalInventory = [
  {name: 'bow'},
  {name: 'sword', progressive: true},
  {name: 'hookshot'},
  {name: 'mushroom'},
  {name: 'powder'},
  {name: 'firerod'},
  {name: 'icerod'},
  {name: 'bombos'},
  {name: 'ether'},
  {name: 'quake'},
  {name: 'lamp'},
  {name: 'hammer'},
  {name: 'flute'},
  {name: 'shovel'},
  {name: 'book'},
  {name: 'bottle'},
  {name: 'somaria'},
  {name: 'byrna'},
  {name: 'cape'},
  {name: 'mirror'},
  {name: 'boots', abutton: true},
  {name: 'glove', abutton: true, progressive: true},
  {name: 'flippers', abutton: true},
  {name: 'mearl', abutton: true},
];
